module.export = {
    products: [
        {
            _id: '1',
            name: 'Llama Shirt',
            category: 'Shirts',
            image: 'images/llama-shirt.jpg',
            price: 59,
            brand: 'Llolo',
            rating: 4.5,
            numReviews: 110,
            countInStock: 16,
        },
        {
            _id: '2',
            name: 'Llama Specs',
            category: 'Specs',
            image: 'images/llama-specs.jpg',
            price: 169,
            brand: 'Lloakley',
            rating: 4,
            numReviews: 90,
            countInStock: 6,
        },
        {
            _id: '3',
            name: 'Llama Chain',
            category: 'Chains',
            image: 'images/llama-chain.jpg',
            price: 249,
            brand: 'Llaxxon',
            rating: 5,
            numReviews: 210,
            countInStock: 15,
        },
        {
            _id: '4',
            name: 'Llama Shoes',
            category: 'Shoes',
            image: 'images/llama-shoes.jpg',
            price: 80,
            brand: 'Lletchers',
            rating: 3.5,
            numReviews: 65,
            countInStock: 5,
        },
        {
            _id: '5',
            name: 'Llama Shirt2',
            category: 'Shirts',
            image: 'images/llama-shirt2.jpg',
            price: 59,
            brand: 'Llolo',
            rating: 4.5,
            numReviews: 95,
            countInStock: 8,
        },
        {
            _id: '6',
            name: 'Llama Specs2',
            category: 'Specs',
            image: 'images/llama-specs2.jpg',
            price: 149,
            brand: 'Lloakley',
            rating: 4,
            numReviews: 55,
            countInStock: 3,
        },
    ],
}